### ISSUE TITLE
Multiple CAA and/or TXT records not possible

### ISSUE THREAD

**Issue by kommulu** [terraform-providers/terraform-provider-powerdns#55]
Terraform Version

Terraform v0.12.21

    provider.powerdns v1.3.0

Affected Resource(s)

powerdns_record

### Terraform Configuration Files
```hcl
resource "powerdns_record" "spf" {
  zone    = "example.com."
  name    = "example.com."
  type    = "TXT"
  ttl     = 60
  records = ["\"v=spf1 mx -all\""]
}

resource "powerdns_record" "dmarc" {
  zone    = "example.com."
  name    = "example.com."
  type    = "TXT"
  ttl     = 60
  records = ["\"v=DMARC1; p=reject; rua=mailto:postmaster@example.com; ruf=mailto:postmaster@example.com; aspf=s; adkim=s\""]
}

resource "powerdns_record" "dkim" {
  zone    = "example.com."
  name    = "example.com."
  type    = "TXT"
  ttl     = 60
  records = ["\"v=DKIM1 ;k=rsa; s=email; p=Msdsdfsdfsdfsdfsdfsdfsdfsdfsdfsfdfsdfsdfsdfds\""]
}

resource "powerdns_record" "caa1" {
  zone    = "example.com."
  name    = "example.com."
  type    = "CAA"
  ttl     = 60
  records = ["0 issue \"letsencrypt.org\""]
}

resource "powerdns_record" "caa2" {
  zone    = "example.com."
  name    = "example.com."
  type    = "CAA"
  ttl     = 60
  records = ["0 issuewild \";\""]
}
```

### Expected Behavior
Terraform creates the defined CAA- and TXT-Records.

### Actual Behavior
Terraform just juggles around the records. At first run, maybe the spf-record is created and caa1.
On the next apply, caa1 is replaced by caa2 and spf is replaced by maybe dmarc.

### Steps to Reproduce
1. `terraform apply`
2. look at your dns entries
3. `terraform apply`
4. check dns again, you should have different entries now

**Comment by mbag** [comment]
Terraform powerdns plugin works by calling PowerDNS API, so if you use same record `name` and `type` with multiple records, but with different `records` value, it will replace any `records` value, that was previously set. The reason you don't see consistency, is because terraform executes resource manipulation in parallel. So sometimes `caa1` gets executed first and sometimes `caa2`.

To have multiple `records` with the same `name` and `type` you have to define those mutliple values in the `records` list (`[]` brackets indicate it's a list, I'll add that to documentation)

I will open pull request with documentation changes and an example about adding multiple records. However quick solution for the above example is to do following:

```
resource "powerdns_record" "txt_spf_dkim" {
  zone    = "example.com."
  name    = "example.com."
  type    = "TXT"
  ttl     = 60
  records = ["\"v=spf1 mx -all\"", "\"v=DKIM1 ;k=rsa; s=email; p=Msdsdfsdfsdfsdfsdfsdfsdfsdfsdfsfdfsdfsdfsdfds\""]
}

resource "powerdns_record" "dmarc" {
  zone    = "axk.io."
  name    = "axk.io."
  type    = "TXT"
  ttl     = 60
  records = ["\"v=DMARC1; p=reject; rua=mailto:postmaster@example.com; ruf=mailto:postmaster@example.com; aspf=s; adkim=s\""]
}

resource "powerdns_record" "caa" {
  zone    = "example.com."
  name    = "example.com."
  type    = "CAA"
  ttl     = 60
  records = ["0 issue \"letsencrypt.org\"", "0 issuewild \";\""]
}

```

**Comment by kommulu** [comment]
Oh man, have I been blind.
Thanks a lot for pointing that out. Works like a charm :)
